name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and restart server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/gurukul

            echo "Resetting and pulling latest changes"
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            echo "Installing dependencies"
            pnpm install

            echo "Approving build scripts"
            pnpm approve-builds || echo "No scripts to approve"

            echo "Killing any existing process on port 4000"
            PID=\$(lsof -t -i:4000 || true)
            if [ -n "\$PID" ]; then
              echo "Killing PID \$PID"
              kill -9 \$PID
            else
              echo "No process running on port 4000"
            fi

            echo "Starting server in background"
            export NODE_ENV=production
            pnpm --filter ./gurukul/gurukul-apps/server/main dev:server:main > server.log 2>&1 &

            echo "Waiting for server to start..."
            sleep 5

            echo "Checking server health"
            if curl -s http://localhost:4000 > /dev/null; then
              echo "✅ Server is running on port 4000"
            else
              echo "❌ Server failed to start or not listening on port 4000"
              exit 1
            fi

            echo "Last few lines of server.log:"
            tail -n 20 server.log

            echo "✅ Deployment complete"
          EOF
