name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and restart server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~
            
            # Clone repo if missing
            if [ ! -d "gurukul/.git" ]; then
              echo "Repository not found. Cloning again..."
              rm -rf gurukul
              git clone https://github.com/Git21221/gurukul.git gurukul
            else
              echo "Repository exists. Pulling latest changes..."
              cd gurukul
              git pull origin main
            fi

            cd gurukul

            echo "Installing dependencies"
            pnpm install

            # Kill any existing server on port 4000
            PID=$(lsof -t -i:4000)
            if [ -n "$PID" ]; then
              echo "Killing process on port 4000 (PID: $PID)"
              kill -9 $PID
            fi

            echo "Starting server"
            export NODE_ENV=production
            pnpm run dev:server:main > server.log 2>&1 &

            echo "Deployment complete"
          EOF
