name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    # paths:
    #   - 'gurukul/gurukul-apps/server/main/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Connecting to EC2..."

            cd ~/gurukul

            echo "Pulling latest changes from main branch"
            git pull origin main

            echo "Killing any existing server on port 4000"
            PID=$(lsof -t -i:4000)
            if [ -n "$PID" ]; then
              echo "Killing process on port 4000 (PID: $PID)"
              kill -9 $PID
            fi

            echo "Installing dependencies"
            pnpm install

            echo "Starting backend server in background"
            pnpm run dev:server:main > server.log 2>&1 &

            echo "Deployment complete"
          EOF
