name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and restart server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/gurukul

            echo "Pulling latest changes from main branch"
            git reset --hard HEAD
            git clean -fd
            git pull origin main

            echo "Killing any existing server on port 4000"
            PID=$(lsof -t -i:4000)
            if [ -n "$PID" ]; then
              echo "Killing process on port 4000 (PID: $PID)"
              kill -9 $PID
            fi

            echo "Installing dependencies"
            pnpm install

            echo "Approving build scripts"
            pnpm approve-builds || echo "No build scripts to approve or already approved."

            echo "Starting the server"
            export NODE_ENV=production
            pnpm --filter ./gurukul/gurukul-apps/server/main dev:server:main > server.log 2>&1 &

            echo "Last few lines of server.log:"
            sleep 3
            tail -n 20 server.log

            echo "Deployment script finished."
          EOF
